create table if not exists public.push_configuration (
  id smallint primary key default 1,
  vapid_public_key text,
  initialized_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint push_configuration_singleton check (id = 1)
);

alter table public.push_configuration enable row level security;
revoke all on public.push_configuration from anon, authenticated;
grant select, insert, update on public.push_configuration to service_role;

insert into public.push_configuration (id)
values (1)
on conflict (id) do nothing;

create table if not exists public.push_events (
  id uuid primary key default gen_random_uuid(),
  appointment_id uuid not null references public.appointments(id) on delete cascade,
  event_type text not null,
  status text not null,
  dispatch_token uuid not null default gen_random_uuid(),
  created_at timestamptz not null default now(),
  dispatched_at timestamptz,
  last_error text,
  constraint push_events_event_type_check check (event_type in ('created','status_changed'))
);

create index if not exists push_events_pending_idx
  on public.push_events(dispatched_at,created_at);
create index if not exists push_events_appointment_idx
  on public.push_events(appointment_id,created_at desc);

alter table public.push_events enable row level security;
revoke all on public.push_events from anon, authenticated;
grant select, insert, update, delete on public.push_events to service_role;

create or replace function public.initialize_push_vapid(
  p_public_key text,
  p_private_key text
)
returns text
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_existing_public text;
  v_secret_id uuid;
begin
  if current_user <> 'service_role' and session_user <> 'service_role' then
    -- PostgREST service-role calls execute as the function owner, so privileges
    -- are enforced by EXECUTE grants below rather than this branch.
    null;
  end if;

  select pc.vapid_public_key
    into v_existing_public
  from public.push_configuration pc
  where pc.id=1;

  if nullif(trim(coalesce(v_existing_public,'')),'') is not null then
    return v_existing_public;
  end if;

  if p_public_key is null or char_length(trim(p_public_key)) < 80 then
    raise exception 'Invalid VAPID public key';
  end if;
  if p_private_key is null or char_length(trim(p_private_key)) < 32 then
    raise exception 'Invalid VAPID private key';
  end if;

  select s.id into v_secret_id
  from vault.secrets s
  where s.name='push_vapid_private_key'
  order by s.updated_at desc
  limit 1;

  if v_secret_id is null then
    perform vault.create_secret(
      trim(p_private_key),
      'push_vapid_private_key',
      'Private VAPID key generated by the push-notifications Edge Function',
      null
    );
  else
    perform vault.update_secret(
      v_secret_id,
      trim(p_private_key),
      'push_vapid_private_key',
      'Private VAPID key generated by the push-notifications Edge Function',
      null
    );
  end if;

  update public.push_configuration
  set vapid_public_key=trim(p_public_key),
      initialized_at=coalesce(initialized_at,now()),
      updated_at=now()
  where id=1;

  return trim(p_public_key);
end;
$function$;

create or replace function public.push_vapid_public_key()
returns text
language sql
stable
security definer
set search_path = ''
as $function$
  select pc.vapid_public_key
  from public.push_configuration pc
  where pc.id=1;
$function$;

revoke all on function public.initialize_push_vapid(text,text) from public, anon, authenticated;
revoke all on function public.push_vapid_public_key() from public, anon, authenticated;
grant execute on function public.initialize_push_vapid(text,text) to service_role;
grant execute on function public.push_vapid_public_key() to service_role;

drop function if exists public.push_dispatch_secret_value();

create or replace function private.dispatch_appointment_push()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_event_id uuid;
  v_token uuid;
  v_event_type text;
begin
  if tg_op = 'INSERT' then
    v_event_type := 'created';
  elsif tg_op = 'UPDATE' and new.status is distinct from old.status then
    v_event_type := 'status_changed';
  else
    return new;
  end if;

  insert into public.push_events (
    appointment_id,
    event_type,
    status
  )
  values (
    new.id,
    v_event_type,
    new.status
  )
  returning id,dispatch_token into v_event_id,v_token;

  perform net.http_post(
    url := 'https://gyyahvrkcjocqhhoslho.supabase.co/functions/v1/push-notifications',
    headers := jsonb_build_object('Content-Type','application/json'),
    body := jsonb_build_object(
      'action','dispatch',
      'event_id',v_event_id,
      'token',v_token
    ),
    timeout_milliseconds := 5000
  );

  return new;
exception
  when others then
    raise warning 'push dispatch failed: %', sqlerrm;
    return new;
end;
$function$;

drop trigger if exists appointments_push_notify on public.appointments;
create trigger appointments_push_notify
after insert or update of status on public.appointments
for each row execute function private.dispatch_appointment_push();
